package errs

import "errors"

var (
	ErrDBUnavailable        = errors.New("db is not available at the moment")
	ErrNotFound             = errors.New("not found")
	ErrAccountNotActive     = errors.New("account is not active")
	ErrUserNotActive        = errors.New("user is not active")
	ErrCreditNotActive      = errors.New("credit is not active")
	ErrInvalidFullName      = errors.New("invalid full name")
	ErrPasswordTooShort     = errors.New("password too short")
	ErrUserAlreadyExists    = errors.New("user with this name already exists")
	ErrInvalidPassword      = errors.New("invalid password")
	ErrInvalidCurrency      = errors.New("invalid currency")
	ErrInvalidInterestRate  = errors.New("interest rate must be between 0.0 and 100.0")
	ErrInsufficientFunds    = errors.New("insufficient funds")
	ErrAccountExists        = errors.New("account exists")
	ErrCreditsExists        = errors.New("credits exists")
	ErrDepositsExists       = errors.New("deposits exists")
	ErrCreateHash           = errors.New("faced an error creating hash")
	ErrGenerateToken        = errors.New("faced an error generating token")
	ErrDepositNotActive     = errors.New(" deposit not active")
	ErrEarlyCloseNotAllowed = errors.New("early closure of deposit is not allowed")
	ErrInvalidAmount        = errors.New("amount must be greater than 0")
	ErrInvalidDuration      = errors.New("invalid duration: must be > 0 and within allowed limits")
	ErrAccountAlreadyExists = errors.New("account already exists")
	ErrFraud                = errors.New("someone is trying to break in to our system")
	ErrNoZeroBalance        = errors.New("cannot delete account with non-zero balance")
	ErrInsufficientBalance  = errors.New("insufficient balance")
)
